[Settings]

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

  # Directory with the lambda functions to deploy to AWS.
  functions = "./functions/"

# A redirect rule with all the supported properties
[[redirects]]
  from = "https://madbatter.netlify.com/*"
  to = "https://www.madbatterbake.com/:splat 301!"

  # By default, redirects won't be applied if there's a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

