[Settings]

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

  # Directory with the lambda functions to deploy to AWS.
  functions = "./functions/"
  environment = { NODE_VERSION = "20.18.0" }
